site_name: Opteryx
site_url: https://opteryx.dev/
site_author: Justin Joyce
site_description: A SQL-on-everything Query Engine you can execute over multiple databases and file formats. Query your data, where it lives.
copyright: Copyright &copy; 2021 - 2025 Justin Joyce (@joocer)

theme:
  name: material
  logo: icarus-opteryx.png
  favicon: icarus-opteryx.png
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
  custom_dir: docs/overrides

repo_name: mabel-dev/opteryx
repo_url: https://github.com/mabel-dev/opteryx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 2

extra_css:
  - stylesheets/extra.css

plugins:
  - termynal

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/qpv2tr989x
    - icon: fontawesome/brands/github 
      link: https://github.com/mabel-dev/opteryx
    - icon: fontawesome/brands/python 
      link: https://pypi.org/project/opteryx/
    - icon: fontawesome/brands/mastodon 
      link: https://mastodon.social/@opteryx

# Page tree
nav:
  - HOME: index.md
  - GET STARTED:
    - get-started/overview.md
    - Quickstart: get-started/quickstart.md
    - CLI API: get-started/command-line-guide.md
    - Python API: get-started/python-client.md
    - Guides:
      - Overview: get-started/guides/index.md
      - Use with Jupyter Notebooks: get-started/guides/using-opteryx-with-jupyter.md
      - Data Sources:
        - Iceberg Integration: get-started/guides/iceberg-and-opteryx.md
        - AWS S3 Storage: get-started/guides/s3-and-opteryx.md
        - Google Cloud Storage: get-started/guides/gcs-and-opteryx.md
      - SQL Databases:
        - Connect to BigQuery: get-started/guides/bigquery-and-opteryx.md
        - Connect to PostgreSQL: get-started/guides/postgres-and-opteryx.md
        - Connect to MySQL: get-started/guides/mysql-and-opteryx.md
        - Connect to DuckDB: get-started/guides/duckdb-and-opteryx.md
        - Connect to SQLite: get-started/guides/sqlite-and-opteryx.md
      - DataFrames:
        - Pandas Integration: get-started/guides/pandas-and-opteryx.md
        - Polars Integration: get-started/guides/polars-and-opteryx.md
      - File Operations:
        - Execute SQL on CSV Files: get-started/guides/execute-sql-on-csv.md
        - Convert CSV to Parquet: get-started/guides/convert-csv-to-parquet.md
    - Deployment Guide: get-started/deployment-guide.md
#    - Configuration Guide: get-started/configuration-guide.md
    - Security: get-started/security.md
    - Ecosystem:
      - Streaming Writer (Mabel): get-started/ecosystem/mabel.md
      - Connector (mesos): get-started/ecosystem/mesos.md
    - Standards & Benchmarks:
      - Python PEP249: get-started/external-standards/pep249.md
      - ANSI SQL-92: get-started/external-standards/sql92.md
      - TPC-H: get-started/external-standards/tpch.md
      - Clickbench: get-started/external-standards/clickbench.md
#      - Information Schema: get-started/external-standards/information-schema.md
    - Release Notes:
      - Change Log: get-started/release-notes/change-log.md
      - Notices: get-started/release-notes/notices.md
  - SQL REFERENCE:
    - sql-reference/introduction.md
    - Statements: sql-reference/statements.md
    - Data Types: sql-reference/data-types.md
    - Expressions: sql-reference/expressions.md
    - Functions: sql-reference/functions.md
    - Aggregates: sql-reference/aggregates.md
    - Joins: sql-reference/joins.md
    - Advanced:
      - Working with Timestamps: sql-reference/adv-working-with-timestamps.md
      - Working with Lists: sql-reference/adv-working-with-lists.md
      - Working with Structs: sql-reference/adv-working-with-structs.md
      - Working with IPs: sql-reference/adv-working-with-ips.md
      - Time Travel: sql-reference/adv-time-travel.md
      - Null Semantics: sql-reference/adv-null-semantics.md
      - Temporary Tables: sql-reference/adv-temp-tables.md
      - Sample Data: sql-reference/adv-sample-data.md
#      - Information Schema: sql-reference/adv-information-schema.md
#      - Engine Configuration: sql-reference/adv-engine-configuration.md
      - Query Optimization: sql-reference/adv-query-optimization.md
  - CONTRIBUTING:
      - contributing/contributing.md
      - Project Goals: contributing/project-goals.md
      - Code of Conduct: contributing/code-of-conduct.md
      - Etiquette: contributing/etiquette.md
      - Set Up Guides:
        - Debian/Ubuntu: contributing/set-up-guides/debian.md
        - MacOS: contributing/set-up-guides/macos.md
      - System Internals:
        - Project Structure: contributing/internals/project-structure.md
        - Query Engine: contributing/internals/query-engine.md
        - Storage Engine: contributing/internals/storage-engine.md
        - Optimization Strategies: contributing/internals/optimization-strategies.md
        - Implementation:
          - Memory Pool: contributing/internals/implementations/memory_pool.md
          - Storage IO: contributing/internals/implementations/storage_io.md
      - Features:
        - Debug Logging: contributing/topics/debug_logging.md
        - Dependency Management: contributing/topics/dependencies.md
        - Testing Approach: contributing/topics/testing.md

