site_name: Opteryx
site_url: https://mabel-dev.github.io/opteryx/latest/
site_author: Justin Joyce
site_description: Opteryx - Query your data, where it lives.
copyright: Copyright &copy; 2021 - 2023 Justin Joyce (@joocer)

theme:
  name: material
  logo: icarus-opteryx.png
  favicon: icarus-opteryx.png
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
  custom_dir: docs/overrides

repo_name: mabel-dev/opteryx
repo_url: https://github.com/mabel-dev/opteryx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 2

extra_css:
  - stylesheets/extra.css

plugins:
  - termynal

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/opteryxsql
    - icon: fontawesome/brands/gitter 
      link: https://gitter.im/mabel-opteryx/community
    - icon: fontawesome/brands/github 
      link: https://github.com/mabel-dev/opteryx
    - icon: fontawesome/brands/python 
      link: https://pypi.org/project/opteryx/

# Page tree
nav:
  - Home: index.md
  - Get Started:
    - get-started/overview.md
    - Get Started: get-started/get-started.md
    - Client Overview: get-started/clients.md
    - Python Guide:
      - get-started/guides/python-client.md
      - Pandas Integration: get-started/guides/pandas-and-opteryx.md
      - Polars Integration: get-started/guides/polars-and-opteryx.md
    - Deployment Guide: get-started/deployment-guide.md
    - Configuration Guide: get-started/configuration-guide.md
    - Security: get-started/security.md
    - Ecosystem:
      - Dataframe (orso): get-started/ecosystem/orso.md
      - Metastore (Tarchia): get-started/ecosystem/metastore.md
      - Storage Engine (HadroDB): get-started/ecosystem/hadrodb.md
      - Streaming Writer (Mabel): get-started/ecosystem/mabel.md
      - Connector (Mesos): get-started/ecosystem/mesos.md
    - Standards & Benchmarks:
      - Python PEP249: get-started/external-standards/pep249.md
      - ANSI SQL-92: get-started/external-standards/sql92.md
      - TPC-H: get-started/external-standards/tpch.md
      - Information Schema: get-started/external-standards/information-schema.md
    - Release Notes:
      - Change Log: get-started/release-notes/change-log.md
      - Notices: get-started/release-notes/notices.md
  - SQL Reference:
    - sql-reference/introduction.md
    - Statements: sql-reference/statements.md
    - Data Types: sql-reference/data-types.md
    - Expressions: sql-reference/expressions.md
    - Functions: sql-reference/functions.md
    - Aggregates: sql-reference/aggregates.md
    - Joins: sql-reference/joins.md
    - Advanced:
      - Working with Timestamps: sql-reference/adv-working-with-timestamps.md
      - Working with Lists: sql-reference/adv-working-with-lists.md
      - Working with Structs: sql-reference/adv-working-with-structs.md
      - Working with IPs: sql-reference/adv-working-with-ips.md
      - Time Travel: sql-reference/adv-time-travel.md
      - Null Semantics: sql-reference/adv-null-semantics.md
      - Temporary Tables: sql-reference/adv-temp-tables.md
      - Sample Data: sql-reference/adv-sample-data.md
      - Information Schema: sql-reference/adv-information-schema.md
      - Engine Configuration: sql-reference/adv-engine-configuration.md
      - Query Optimization: sql-reference/adv-query-optimization.md
  - Contributing:
      - contributing/contributing.md
      - Code of Conduct: contributing/code-of-conduct.md
      - Etiquette: contributing/etiquette.md
      - Set Up Guides:
        - Debian/Ubuntu: contributing/set-up-guides/debian.md
        - MacOS: contributing/set-up-guides/macos.md
        - Windows: contributing/set-up-guides/windows.md
      - System Internals:
        - Project Structure: contributing/internals/project-structure.md
        - Query Engine: contributing/internals/query-engine.md
        - Storage Engine: contributing/internals/storage-engine.md
        - Testing Approach: contributing/internals/testing.md
      - Version Goals: contributing/version-goals.md
  - Blog:
      - Year 2022:
        - Building our first Optimizer: blog/202209-building-our-first-optimizer.md

