---

    name: Quality Checks
    
    on:
      push
    
    jobs:
      regression_matrix:
        strategy:
          max-parallel: 4
          fail-fast: false
          matrix:
            python-version: ['3.12']
        runs-on: ubuntu-latest
        steps:
    
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Set up Python ${{ matrix.python-version }} x64
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
              architecture: x64
    
          - name: Install Requirements
            run: |
              python -m pip install --upgrade pip
              python -m pip install --upgrade pytest
    
          - name: Run Regression Tests
            run: python -m pytest
    