name: Documentation
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: 'Deploy Documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: git config user.name XB500
      - run: git config user.email XB500@users.noreply.github.com
      - run: git fetch origin gh-pages --depth=1
      - run: pip install --upgrade mkdocs-material mike termynal
  
      # this should match the version
      #- run: mike delete latest
      #- run: mike deploy -p "0.8.3" latest
      #- run: mike delete dev
 
      - run: mike deploy -p "0.9.0" dev      